### ISSUE TITLE
Cryptodome: considered as a Trojan from Kaspersky AV

### ISSUE THREAD

**Issue by lbartoletti** [mod-audio/mod-desktop#66]
Hi,

I wanted to test the mod-desktop and encoutering an issue on windows with Kaspersky AntiVirus:

French log from Kaspersky
```
Nom de l'application: mod-desktop-0.0.12-win64-installer.tmp
Chemin d'accès à l'application: C:\Users\xxxx\AppData\Local\Temp\is-TDCBL.tmp
Module: Antivirus fichiers
Résultat de description: Détecté
Type: Cheval de Troie
Nom: VHO:Trojan.Win32.Agent.gen
Exactitude: Analyse heuristique
Niveau de menace: Élevé
Type d'objet: Fichier
Nom de l'objet: _cpuid_c.pyd
Chemin de l'objet: C:\Program Files\MOD Desktop\lib\Cryptodome\Util
```

English translation:

Kaspersky considers `_cpuid_c.pyd` from `C:\Program Files\MOD Desktop\lib\Cryptodome\Util` as a Trojan (Trojan.Win32.Agent.gen)

**Comment by lbartoletti** [comment]
And same for `_cpuid_c.abi3.so`

**Comment by falkTX** [comment]
that is expected, anything that relates to getting cpu id is flagged as being dangerous.

nothing to do here, this is a false positive.
